name: News from Brazil
favicon: null
layout_spectrum: 0.73727
typography_spectrum: 0.76642
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#282828'
    - '#a29f8c'
    - '#e2dccc'
    - '#7b5137'
  brandStrength: 0.6996025370899588
  lightness: 1
  saturation: 0
  rhythmicContrast: 0.5
purpose: []
