name: News from Brazil
favicon: null
layout_spectrum: 0.73727
typography_spectrum: 0.7955781286582351
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#7ec2ff'
    - '#12121c'
    - '#ffffff'
    - '#8a8a8a'
    - '#925e49'
  brandStrength: 0.6996025370899588
  lightness: 1
  saturation: 0
  rhythmicContrast: 0.5
purpose: []
